### ISSUE TITLE
Few bugs I came across

### ISSUE THREAD

**Issue by Hikandy** [RadioNoiseE/exposway#2]
1. I'm unable to select the window in the overview with my cursor and it seems like the only way to select is using keys.
2. The selection seems to quite slow? As in, when i move around using the arrow keys, its not instantaneous and takes like about half a second to go the selection

**Comment by RadioNoiseE** [comment]
> 1. I'm unable to select the window in the overview with my cursor and it seems like the only way to select is using keys.

Currently, yes (as mentioned in the README). I'm concerned that currently it may add extra complexity, so my recent plan is to optimize things like the layout algorithm, frame redraw, animation and such things.

> 2. The selection seems to quite slow? As in, when i move around using the arrow keys, its not instantaneous and takes like about half a second to go the selection

Try change the value of`DEBOUNCE_DELAY_MS` in `expose.h` to a smaller one and see if it works. If the delay still exists then that's because the window traversing algorithm (I am planning to optimize it anyway).

**Comment by RadioNoiseE** [comment]
The window traversing algorithm has been fixed, and the default `DEBOUNCE_DELAY_MS` has been changed to a smaller value.
